services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: measure_ai
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/shopperTest
      - GEMINI_API_KEY=${GEMINI_API_KEY} 
    env_file:
      - .env 
    ports:
      - "3000:3000" # Expose the port in the .env file.
    volumes:
      - ./temp:/usr/src/app/temp
    command: sh -c "npx prisma migrate deploy && npm run start"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopperTest
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  node_modules:
