services:
  app:
    image: node:22
    container_name: measure_ai
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - /app/temp # Anonymous volume for the images.
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/shopperTest
      - GEMINI_API_KEY=${GEMINI_API_KEY} 
    env_file:
      - .env 
    ports:
      - "3000:3000" # Expose the port in the .env file.
    command: sh -c "mkdir -p /app/temp && npm install && npx prisma migrate deploy && npm run deploy"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopperTest
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  node_modules:
